// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVXyT5WvvyVE5fSNIWmBZMDoqqaejSfn4',
    appId: '1:688553563392:web:7565a2f0408dbe47150fe5',
    messagingSenderId: '688553563392',
    projectId: 'elearning-edspert-trial',
    authDomain: 'elearning-edspert-trial.firebaseapp.com',
    storageBucket: 'elearning-edspert-trial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr1E84Fjh26s0DXWZBblLuEQg8z3siJt0',
    appId: '1:688553563392:android:262fdec29358b7b5150fe5',
    messagingSenderId: '688553563392',
    projectId: 'elearning-edspert-trial',
    storageBucket: 'elearning-edspert-trial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG3T7PefFAHTV6rtRi_HGTfzfTgOeipXE',
    appId: '1:688553563392:ios:c89cc1068fa3c077150fe5',
    messagingSenderId: '688553563392',
    projectId: 'elearning-edspert-trial',
    storageBucket: 'elearning-edspert-trial.appspot.com',
    iosBundleId: 'com.example.flutterAdvance',
  );
}
